"""empty message

Revision ID: 936798045796
Revises: 
Create Date: 2025-02-18 20:59:04.239404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936798045796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('dpi', sa.String(length=15), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dpi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    # ### end Alembic commands ###
