"""empty message

Revision ID: 9db6dcd2630a
Revises: ad94811007e3
Create Date: 2025-02-25 20:48:54.934620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db6dcd2630a'
down_revision = 'ad94811007e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exc_zanja', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('mat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('mo',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    with op.batch_alter_table('exc_zanja_item', schema=None) as batch_op:
        batch_op.alter_column('rendimiento_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('dist',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('dist_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_galon',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_dist',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('factor',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    with op.batch_alter_table('exc_zanja_plantilla', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exc_zanja_plantilla', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('exc_zanja_item', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_dist',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_galon',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dist_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dist',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('rendimiento_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('exc_zanja', schema=None) as batch_op:
        batch_op.alter_column('mo',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mat',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
