"""empty message

Revision ID: ad94811007e3
Revises: 39ddc7b65a36
Create Date: 2025-02-25 12:26:37.607858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad94811007e3'
down_revision = '39ddc7b65a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exc_zanja_plantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia', sa.String(length=15), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('unidad_metrica', sa.String(length=5), nullable=True),
    sa.Column('cantidad', sa.Float(precision=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exc_zanja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exc_zanja_plantilla_id', sa.Integer(), nullable=False))
        batch_op.alter_column('cantidad',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('mat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('mo',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'exc_zanja_plantilla', ['exc_zanja_plantilla_id'], ['id'])
        batch_op.drop_column('familia')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('exc_zanja_item', schema=None) as batch_op:
        batch_op.alter_column('rendimiento_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('dist',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('dist_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_hora',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_galon',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('valor_dist',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
        batch_op.alter_column('factor',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exc_zanja_item', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_dist',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_galon',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dist_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('dist',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('rendimiento_hora',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('exc_zanja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('familia', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mo',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('mat',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('exc_zanja_plantilla_id')

    op.drop_table('exc_zanja_plantilla')
    # ### end Alembic commands ###
