"""empty message

Revision ID: f9e3214a2c32
Revises: 936798045796
Create Date: 2025-02-18 21:14:50.613120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e3214a2c32'
down_revision = '936798045796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_representante', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
